# Author : sjh8543@gmail.com
# This images is made to test ab-testing engine. It can be rebuild later with another structure. 
FROM flask-app:0.3

RUN mkdir flask_app/test
COPY main_test.py flask_app/test/main_test.py
